### ISSUE TITLE
Replace 'pickle' with custom json encoder (SVC)

### ISSUE THREAD

**Issue by jeff1evesque** [jeff1evesque/machine-learning#1755]
We will consider replacing the `pickle` [implementation](https://github.com/jeff1evesque/machine-learning/issues/1752) in `serialize_model.py` with a custom json encoder, and custom json decoder for the SVC instance.

**Comment by jeff1evesque** [comment]
The following shows explicit properties contained within the scikit-learn [`SVC`](http://scikit-learn.org/stable/modules/generated/sklearn.svm.SVC.html#sklearn.svm.SVC) class:

```python
$ python
Python 2.7.6 (default, Mar 22 2014, 22:59:56) 
[GCC 4.8.2] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> from sklearn import svm
>>> X = [[0, 0], [1, 1]]
>>> y = [0, 1]
>>> clf = svm.SVC()
>>> clf.fit(X, y)
SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0, degree=3, gamma=0.0,
  kernel='rbf', max_iter=-1, probability=False, random_state=None,
  shrinking=True, tol=0.001, verbose=False)
>>> vars(clf)
{'_impl': 'c_svc', 'kernel': 'rbf', 'verbose': False, 'probability': False, 'classes_': array([0, 1]), 'support_': array([0, 1], dtype=int32), 'dual_coef_': array([[ 1., -1.]]), 'shrinking': True, 'class_weight': None, '_gamma': 0.5, 'probA_': array([], dtype=float64), '_sparse': False, 'class_weight_': array([ 1.,  1.]), 'random_state': None, 'tol': 0.001, 'coef0': 0.0, 'nu': 0.0, 'n_support_': array([1, 1], dtype=int32), 'shape_fit_': (2, 2), 'C': 1.0, 'support_vectors_': array([[ 0.,  0.],
       [ 1.,  1.]]), 'degree': 3, 'epsilon': 0.0, 'max_iter': -1, 'fit_status_': 0, '_intercept_': array([ 0.]), 'intercept_': array([-0.]), 'probB_': array([], dtype=float64), 'cache_size': 200, 'gamma': 0.0}
```

**Comment by jeff1evesque** [comment]
If we attempt to serialize the `SVC` class properties, we notice the the containing numpy array is not serializable:

```python
>>> clf
SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0, degree=3, gamma=0.0,
  kernel='rbf', max_iter=-1, probability=False, random_state=None,
  shrinking=True, tol=0.001, verbose=False)
>>> type(vars(clf))
<type 'dict'>
>>> import json
>>> serialized = json.dumps(vars(clf))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python2.7/json/__init__.py", line 243, in dumps
    return _default_encoder.encode(obj)
  File "/usr/lib/python2.7/json/encoder.py", line 207, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python2.7/json/encoder.py", line 270, in iterencode
    return _iterencode(o, 0)
  File "/usr/lib/python2.7/json/encoder.py", line 184, in default
    raise TypeError(repr(o) + " is not JSON serializable")
TypeError: array([0, 1]) is not JSON serializable
```

Therefore, we need to add logic that replaces numpy array instances with a python lists.  Then, we can perform the `json.dumps` operation.

**Comment by jeff1evesque** [comment]
The following logic runs at linear time:

```python
>>> clf
SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0, degree=3, gamma=0.0,
  kernel='rbf', max_iter=-1, probability=False, random_state=None,
  shrinking=True, tol=0.001, verbose=False)
>>> new_dict = vars(clf)
>>> new_dict
{'_impl': 'c_svc', 'kernel': 'rbf', 'verbose': False, 'probability': False, 'classes_': [0, 1], 'support_': [0, 1], 'dual_coef_': [[1.0, -1.0]], 'shrinking': True, 'class_weight': None, '_gamma': 0.5, 'probA_': [], '_sparse': False, 'class_weight_': [1.0, 1.0], 'random_state': None, 'tol': 0.001, 'coef0': 0.0, 'nu': 0.0, 'n_support_': [1, 1], 'shape_fit_': (2, 2), 'C': 1.0, 'support_vectors_': [[0.0, 0.0], [1.0, 1.0]], 'degree': 3, 'epsilon': 0.0, 'max_iter': -1, 'fit_status_': 0, '_intercept_': [0.0], 'intercept_': [-0.0], 'probB_': [], 'cache_size': 200, 'gamma': 0.0}
>>> import numpy
>>> for key, value in new_dict.items():
...   if type(value) == numpy.ndarray:
...     new_dict[key] = value.tolist()
... 
>>> new_dict
{'_impl': 'c_svc', 'kernel': 'rbf', 'verbose': False, 'probability': False, 'classes_': [0, 1], 'support_': [0, 1], 'dual_coef_': [[1.0, -1.0]], 'shrinking': True, 'class_weight': None, '_gamma': 0.5, 'probA_': [], '_sparse': False, 'class_weight_': [1.0, 1.0], 'random_state': None, 'tol': 0.001, 'coef0': 0.0, 'nu': 0.0, 'n_support_': [1, 1], 'shape_fit_': (2, 2), 'C': 1.0, 'support_vectors_': [[0.0, 0.0], [1.0, 1.0]], 'degree': 3, 'epsilon': 0.0, 'max_iter': -1, 'fit_status_': 0, '_intercept_': [0.0], 'intercept_': [-0.0], 'probB_': [], 'cache_size': 200, 'gamma': 0.0}
```

**Comment by jeff1evesque** [comment]
With the above [result](https://github.com/jeff1evesque/machine-learning/issues/1755#issuecomment-100076351), we can cache a json encoded object, instead of a serialized python `pickle` object.  Upon deserializing our json encoded object, we will need to pass the corresponding `dict` attributes to the `SVM` class to reconstruct the class object.

**Comment by jeff1evesque** [comment]
We should also take this opportunity to replace the [pickle](https://github.com/jeff1evesque/machine-learning/blob/248485a6ae21fca7d88b087165039f257d6e43e5/brain/cache/session.py) implementation, for `/login` session.

**Comment by protojas** [comment]
where in the repo do you want me to put this?

**Comment by jeff1evesque** [comment]
Maybe in [`brain/converter/serializer`](https://github.com/jeff1evesque/machine-learning/tree/master/brain/converter)?

**Comment by protojas** [comment]
ok will do

**Comment by protojas** [comment]
I didn't test it with boosting but it should resolve #1755 and #3080 at least.. probably #3081 too

**Comment by protojas** [comment]
the `test_serialize()` passes all the assertions but I don't know whether they function correctly with real data cause I used trivial test cases

**Comment by jeff1evesque** [comment]
@protojas, one good way to test if they work with real data, is to swap out the `pickle` implementation from [`brain/cache/model.py`](https://github.com/jeff1evesque/machine-learning/blob/d2cbc2b35bf55754f45e4202c4cec937eda09c8e/brain/converter/model.py#L38-L55), with your custom json encoder. We already have corresponding svm, and svr unit tests, which will execute your commits. However, the `serialize`, and `deserialize` method may need an additional argument, to signify what type of custom encoder will be used.  I'm not sure if different sklearn models, will have different structures.

**Comment by protojas** [comment]
Bagging does have a different structure from SVC for example, but the encoder as is is written to handle both. i used a generic way of changing a dict back into an object (rather than tailoring it to specific sklearn classifiers) so it shouldn't really matter what type of classifier is given to them, as long as `deserialize` undoes exactly what the `serialize` method did.

how do I run the tests once i've replaced the instances in `brain/cache/model.py` ?

**Comment by jeff1evesque** [comment]
If you have a `vagrant up` instance built, you can `vagrant ssh` into the ubuntu virtualbox:

```bash
root@trusty64:/vagrant/test# ./unit-tests
```

Or, if you feel comfortable with a PR, that will trigger a travis build, which will run the same bash unit test script. I've been suggesting to keep post commits after PR to a minimum, since the bots are autogenerating [feedback](https://github.com/jeff1evesque/machine-learning/pull/3083#issuecomment-338865619), which results in email notifications being sent (not a problem for me).

**Comment by protojas** [comment]
ok i'll run it from vagrant then

**Comment by protojas** [comment]
I added a test for a Boosting Regressor which didn't give any errors..

Also I attempted to run unit-tests but it gave errors with some database stuff (prior to any of my changes to `model.py`) and then it wouldn't let me run the script a second time, citing some error about a daemon not running, even after doing `vagrant destroy` and `vagrant up`.. should I attempt a pull request to get travis to do the tests?

**Comment by jeff1evesque** [comment]
In the future, try to keep the commits granular per issue. So, we can easily look up in the SVC issue, for the custom encoders for svm, and svr, while the baggers, and boosters, will have their corresponding items.

However, I'm not sure why the unit tests would fail a second time. Perhaps your machine, doesn't have enough memory? My laptop has 16GB or ram. Did you run the command in the ubuntu machine:

```bash
root@trusty64:/vagrant/test# ./unit-tests
```

**Comment by jeff1evesque** [comment]
The bash script `unit-tests` basically destroys all docker containers before running, then builds a network of containers, all linked together, and fired `POST` requests at it. When unit tests are complete with the `POST` requests, the docker containers are all stopped, then destroyed.  Then the corresponding `coverage` report, is `cat` to the standard output in the terminal, just like travis builds.

**Comment by jeff1evesque** [comment]
I would make a separation between application logic, and unit tests. You have some unit tests in your `serializer.py`.  But, it would be more appropriate, to migrate that `assert` logic, to the [`test/live_server`](https://github.com/jeff1evesque/machine-learning/tree/master/test/live_server) directory.  More unit tests are never bad, since it would increase code coverage, which is always a good thing. I'd create `test/live_server/4_utility/serializer.py`, and move the unit tests there.

**Comment by jeff1evesque** [comment]
>should I attempt a pull request to get travis to do the tests?

If you're certain that you cannot get the manual unit tests working (it should work), then go ahead and open up a PR. But, before doing so, lets segregate the unit tests.

**Comment by jeff1evesque** [comment]
This last commit looks good. Do you need to run some tests?

**Comment by protojas** [comment]
sorry I thought I commented asking how to do the pull request but I guess it was on the wrong thread or something lol

how should I do the pull request properly for this one?

**Comment by protojas** [comment]
After looking at the errors with deserializing, I think it's best if we keep pickle for now. 

The way to do this generically would be to serialize functions by essentially sending their entire source code and then reinstating those functions in the object. That has a number of security and implementation issues and it's likely that that is a whole new project.

To do this not generically, i.e., creating a separate serializer for each classifier might work in some cases, such as SVC. The serializer would have to assign the internal variables (like the trained model) to a new SVC() object. This would be much more difficult with a BaggingClassifier, though, because a BaggingClassifier stores n models internally, so each would need to be serialized. On top of that, the internal models can also be BaggingClassifiers (or things like Random Forest), making this not only a recursive problem, but also requires the internal models to be identified prior to their serialization. And since each classifier would have their own serializer, the different serializers would need to be used for internal models as well.

**Comment by jeff1evesque** [comment]
Closing this issue, as it wasn't created with ensemble in mind, which adds more layers of complexity.
