### ISSUE TITLE
Strengthen password hash implementation in 'crypto.py'

### ISSUE THREAD

**Issue by jeff1evesque** [jeff1evesque/machine-learning#2747]
We need to rename `load_salt` to `getsalt`, and move the following logic from [`hashpass`](https://github.com/jeff1evesque/machine-learning/blob/bc7e21ffc9d318a56ea11d5cb1aa201ff5df18ed/brain/converter/crypto.py#L43-L45) to the former method, yet to be adjusted:

```python
...
    salt_length = load_salt(app=False)['salt_length']
    salt_length = salt_length if salt_length is not None else 32
    salt = base64.b64encode(os.urandom(salt_length))
...
```

Additionally, we need to replace the existing hashing mechanism, by implementing [scrypt](https://pypi.python.org/pypi/scrypt/) (or some alternate close variation).  This means we'll probably need to change the following from `hashpass`:

```python
...
return hashlib.sha512(salt + p).hexdigest()+"$"+salt
...
```

Then, we can adjust the `return` from `getsalt` to return the `salt` value, instead of the `salt_length`, and implement it respectively within other functions within `crypto.py`.

**Comment by jeff1evesque** [comment]
We need to accurately defend the case for either `sha512`, or `scrypt`.  Either the difference favors the current implementation, then we can make the following trivial changes:

- rename `load_salt` to `getsalt`
- `return` the actual salt value from `getsalt`
- implement `getsalt` within `hashpass`

**Comment by jeff1evesque** [comment]
Per [OWASP]([‎9/‎28/‎2016 10:03 PM](https://www.owasp.org/index.php/Cryptographic_Storage_Cheat_Sheet#Rule_-_Use_strong_approved_cryptographic_algorithms), it seems scrypt is preferred over sha:

>Do not implement an existing cryptographic algorithm on your own, no matter how easy it appears. Instead, use widely accepted algorithms and widely accepted implementations.

>Only use approved public algorithms such as AES, RSA public key cryptography, and SHA-256 or better for hashing. Do not use weak algorithms, such as MD5 or SHA1. Avoid hashing for password storage, instead use PBKDF2, bcrypt or scrypt.

**Comment by protojas** [comment]
```
scrypt-1.2.0/libcperciva/crypto/crypto_aes.c:6:25: fatal error: openssl/aes.h: No such file or directory

 #include <openssl/aes.h>

                         ^

compilation terminated.

error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
```
Motivation for installing libssl-dev

**Comment by protojas** [comment]
```
src/scrypt.c:27:20: fatal error: Python.h: No such file or directory

 #include <Python.h>

                    ^

compilation terminated.

error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
```
Motivation for installing python-dev before scrypt
