### ISSUE TITLE
Fix typo in flask installation script

### ISSUE THREAD

**Issue by protojas** [jeff1evesque/machine-learning#2760]
https://github.com/jeff1evesque/machine-learning/blob/master/puppet/environment/docker/modules/package/manifests/flask_script.pp#L10

https://github.com/jeff1evesque/machine-learning/blob/master/puppet/environment/vagrant/modules/package/manifests/flask_script.pp#L10

Misspelling of 'flask' as 'flack'

**Comment by jeff1evesque** [comment]
Seems like the `ensure =>` attribute can have a null value, causing it to install the latest version.
