### ISSUE TITLE
Implement 'flask-login' for user login and logout

### ISSUE THREAD

**Issue by jeff1evesque** [jeff1evesque/machine-learning#2813]
We need to store logged-in users state, via the [Flask-Login](https://flask-login.readthedocs.io/en/latest/) api.  This means, we'll need to add the corresponding package to our puppet build.  Additionally, we need to create some logic to allow users to logout, after logging in.

**Comment by jeff1evesque** [comment]
We should also enhance our `pytest_user_login.py` to `assert` the corresponding `flask-login` attribute is properly set.  Then, we'll need to add additional unit test, to check the logout succeeded.

**Comment by jeff1evesque** [comment]
When we submit a `/login` request, we get the following error traceback:

```bash
vagrant@vagrant-ubuntu-trusty-64:~$ (cd /vagrant && python app.py)
[2016-11-20 18:07:19,228] ERROR in app: Exception on /login [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1988, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1641, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1544, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1639, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1625, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/vagrant/interface/views.py", line 188, in login
    login_user(username)
  File "/usr/local/lib/python2.7/dist-packages/flask_login/utils.py", line 137, in login_user
    if not force and not user.is_active:
AttributeError: 'unicode' object has no attribute 'is_active'
```

**Comment by jeff1evesque** [comment]
The above latest five commits were attempted on the basis from the following sources:

- https://github.com/boh717/FlaskLogin-and-pymongo
- https://flask-login.readthedocs.io/en/0.4.0/#how-it-works
- http://stackoverflow.com/questions/20136090/how-do-i-handle-login-in-flask-with-multiple-blueprints#answer-36318204

**Comment by jeff1evesque** [comment]
We still get the [same error](https://github.com/jeff1evesque/machine-learning/issues/2813#issuecomment-261813555) as stated earlier.

**Comment by jeff1evesque** [comment]
When we submit a `/login` request, no errors are displayed, as was the case [earlier](https://github.com/jeff1evesque/machine-learning/issues/2813#issuecomment-261813555).

**Comment by jeff1evesque** [comment]
The following sources were reviewed while making the above changes:

- http://docplayer.net/10906236-Flask-web-development-miguel-grinberg.html
- http://flask.pocoo.org/docs/0.11/quickstart/#sessions

**Comment by jeff1evesque** [comment]
The [flask-login](https://github.com/maxcountryman/flask-login) project is a bloated, wrapper to the flask `session` object.  An [issue](https://github.com/maxcountryman/flask-login/issues/324#issuecomment-262389043) was in hopes to acquire hints to solve our earlier attempt.  Instead it was recommended to review stackoverflow articles, which was already reviewed  Since the requirements is to simply provide a mechanism to store the logged in user name, until `logout`, the `session` object can be used directly, instead of the larger convoluted wrapper.

**Comment by jeff1evesque** [comment]
The [flask-login](https://github.com/maxcountryman/flask-login) project is a bloated, wrapper to the flask `session` object.  An [issue](https://github.com/maxcountryman/flask-login/issues/324#issuecomment-262389043) was raised in hopes to acquire hints to solve our earlier attempt.  Instead it was recommended to review stackoverflow articles, which was already reviewed  Since the requirements is to simply provide a mechanism to store the logged in user name, until `logout`, the `session` object can be used directly, instead of the larger convoluted wrapper.

**Comment by doobeh** [comment]
To help clarify why the load_user code is currently having issues, use this code to get a visual debug of what's going on versus expectations:

```python
@login_manager.user_loader
def load_user(uid):
    print("Supplied id is {}".format(uid))
    # local variables
    account = Retrieve_Account()
    email = account.get_email(username)['result']
    print("Result of email check is {}".format(email))
    username = account.get_username(uid)['result']
    print("Result of username check is {}".format(username))

    # return
    if (uid and username and email):
        print("I have a complete set of ingredients for a User object!")
        return User(uid, username, email)

    else:
        print("I failed! I'm missing an ingredient!")
        return None
```

`uid` is a unicode id-- which in the case of your models is `1`, `2` etc.  If you look at your code for `account.get_email(username)` where is username ever set?
