### ISSUE TITLE
Create bootstrap aggregation wrapper (regressor)

### ISSUE THREAD

**Issue by jeff1evesque** [jeff1evesque/machine-learning#3041]
We need to create a python function for the bootstrap aggregation method.  This function, should accept a variety of our predefined estimators:

- `SVR` (#3035)
- `KNeighborsRegressor` (#3033)
- `RandomForestRegressor` (#3039)
- `BaggingRegressor` (#3034)

**Note:** this issue is a successor of #3025.

**Comment by protojas** [comment]
I don't really understand the difference between this and #3034, or between #3042 and #3036 

Unless this is also under the assumption that you can feed existing models into a bagging classifier/regressor.

you can only tell the bagging classifier/regressor which estimator to use internally, you can't give it external models

**Comment by jeff1evesque** [comment]
I did some quick research earlier this summer, and think I came to same conclusion as you did. Unfortunately, I had forgotten what I found this past week.  I think the bagging implementation has it's own built in estimator, unless you have found a way to otherwise implement a different estimator, from say the `SVC` class.  However, if it's not possible at all, to provide an estimator outside the built in boosting classifier, and regressor, we may just close the issues you've stated as confusing.  Basically, consolidate the task into this issue.  This would also apply for #3042, and it's related issues.

**Comment by jeff1evesque** [comment]
I'm making some fixes to your branch.  If you plan on working on this issue again:

```bash
git pull upstream feature-3041
git pull origin feature-3041
```

**Comment by jeff1evesque** [comment]
It seems a lot of things were introduced. But, it's not a bad things, basically I merged the updated `master` into this `feature-3041` branch.

**Comment by jeff1evesque** [comment]
I'll take care of fixing the associated syntax errors, and `merge` the respective PR in a short while.

**Comment by jeff1evesque** [comment]
Closing this issue per https://github.com/jeff1evesque/machine-learning/pull/3061.
