### ISSUE TITLE
Replace 'createClass' with pure javascript classes

### ISSUE THREAD

**Issue by jeff1evesque** [jeff1evesque/machine-learning#3047]
We need to replace all our current reactjs `React.createClass({ // ... })`, with pure javascript classes. This will help avoid the following current warning:

>content.min.js:35 Warning: Accessing createClass via the main React package is deprecated, and will be removed in React v16.0. Use a plain JavaScript class instead. If you're not yet ready to migrate, create-react-class v15.* is available on npm as a temporary, drop-in replacement. For more info see https://fb.me/react-create-class

![createclass](https://user-images.githubusercontent.com/2907085/31544617-a94dc908-afe9-11e7-82cc-270a023708a5.JPG)

**Comment by jeff1evesque** [comment]
A good example, of pure reactjs classes, can be reviewed, via [`user-menu.jsx`](https://github.com/jeff1evesque/machine-learning/blob/43902ce850785247ba023bd0f79a2cb182cfdf03/src/jsx/import/navigation/user-menu.jsx).

**Comment by Vitao18** [comment]
I'll take care of this, ok?

**Comment by jeff1evesque** [comment]
Depending on how long it takes to resolve this issue, be cognizant of other `frontend` issues, that get merged to the `master` branch.  Merge conflicts are usually a good source of human error getting introduced, as contributors try to make their enhancements mergeable. For example, the following two issues are most immediate:

- #3051 
- #3052

However, I'm fairly confident in resolving the above two by tomorrow morning.  So, shouldn't be a problem, unless you have the entire fixes for this issue tonight.

**Comment by Vitao18** [comment]
What do you think is the best option?
Doing all then sending the PR or doing one PR for each file as I do the work?

**Comment by jeff1evesque** [comment]
@Vitao18, do you prefer doing a pull request for each jsx file, or doing one large pull request? I think a larger, all encapsulating issue would make more sense. I think that was the original intent of this issue.

**Comment by jeff1evesque** [comment]
Closing this issue per #3079.
