### ISSUE TITLE
Add bgr ensemble programmatic-api unit test

### ISSUE THREAD

**Issue by jeff1evesque** [jeff1evesque/machine-learning#3067]
We need to unit test the bgr ensemble method, and develop any backend dependency, to allow the programmatic-api, to cooperate with the desired unit test.

**Comment by protojas** [comment]
[classifiers_regressors_wrappers.zip](https://github.com/jeff1evesque/machine-learning/files/1456021/classifiers_regressors_wrappers.zip)

I couldn't find the files I committed to various issues when writing these so here are the wrappers to the bagging regressors and classifiers. they would go into brain/session/model/classifiers and brain/session/model/regressors.. I'll let you worry about which goes under which issue

**Comment by protojas** [comment]
I don't think there's any other changes needed before making the first unit test for this

**Comment by protojas** [comment]
I added the unit tests but they need to be updated with the actual results

**Comment by jeff1evesque** [comment]
I just pushed your commits to travis, and can update them later with the actual values.

**Comment by jeff1evesque** [comment]
This issue has been resolved via https://github.com/jeff1evesque/machine-learning/pull/3110.
