### ISSUE TITLE
Investigate javascript + reactjs unit test framework

### ISSUE THREAD

**Issue by jeff1evesque** [jeff1evesque/machine-learning#3084]
We need to research possible frameworks, to unit test our javascript, and reactjs scripts. The following are some possible options, though other may be equally considered:

- [jest](http://facebook.github.io/jest/docs/en/tutorial-react.html)
- [ava](https://github.com/avajs/ava)
- [sazerac](https://github.com/mikec/sazerac)

**Note:** this issue is intended to simply investigate viable options, and lead to further issues, for actual implementation, of the corresponding unit test method.

**Comment by Vitao18** [comment]
Some good links on this subject:
http://facebook.github.io/jest/docs/en/tutorial-react.html
https://www.testingexcellence.com/test-automation-tools-for-testing-reactjs-applications/ 

The second link states the best way to run unit tests in React is [Mocha](https://github.com/mochajs/mocha)+[Enzyme](https://github.com/airbnb/enzyme).
From what I've read, Enzyme makes the testing syntax easy and is the way to go.
Jest is kinda of slow and have confusing Mock, but requires the least configuration.

I like the almost-no-configuration approach(Jest)

**Comment by jeff1evesque** [comment]
I like jest, since it seems to be able to unit test both reactjs, and vanilla javascript. Could you find out how to integrate jest tests with travis ci. From quick skimming around, it seems istanbul is built into jest. What we'll need to find out, is how to integrate jest + istanbul into coverage reports for travis ci.

**Comment by jeff1evesque** [comment]
I think in order to have multiple unit tests, we would have to converge all reports into a single `.coverage/results.json`. This would be related to the badge on the [`README.md`](https://github.com/jeff1evesque/machine-learning/blob/master/README.md), which shows how much of our code is covered under unit tests.  This is something I enjoy enough doing. So, maybe you can investigate the necessary syntax, using a tool, which could appropriately generate a `results.json`.

**Note:** the badge associated with `build|failing`, or `build|passing`, that's something I could do easily.

**Comment by Vitao18** [comment]
Good!
I'll start learning how to test using Travis CI with the Jest+Enzyme also learning how to test!
I'm gonna let you know of what I find in the way

**Comment by jeff1evesque** [comment]
Don't worry so much about the Travis initially. If you must, make sure whatever tool you use is compatible with a tool like coveralls. Jest should have a thing called Istanbul, which should play nice with coveralls. If that's the case, I can connect the report output `.coverage/results.json` to the Travis CI.

**Comment by jeff1evesque** [comment]
Closing this issue, since work will now be done in #3087.
