### ISSUE TITLE
sudo:docker:command not found

### ISSUE THREAD

**Issue by chickuvlm** [jeff1evesque/machine-learning#3109]
![screen shot 2017-11-12 at 2 27 50 pm](https://user-images.githubusercontent.com/33593593/32697391-9359ffa2-c7b5-11e7-992a-156f1cf0c1cb.png)

i can't proceed with unit test.showing command not found

**Comment by jeff1evesque** [comment]
These tests, are intended to help me with development for this repository. So, if you've been having problems running it so far, I would concern yourself with other more important things. Three different issues, with two github accounts, for the same trivial issue, is not acceptable. Please use your original #3017.

**Comment by chickuvlm** [comment]
![screen shot 2017-11-14 at 2 37 22 pm](https://user-images.githubusercontent.com/33593593/32771674-798785aa-c949-11e7-8e38-926f64e87d15.png)

how to solve this
